---
apiVersion: v1
kind: Namespace
metadata:
  name: vault
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-7"
  labels:
    create-ca-bundle: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-kes-secret
  namespace: vault
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "-8"
    replicator.v1.mittwald.de/replicate-from: minio-tenant/minio-kes-secret
data: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-certificate
  namespace: vault
  annotations:    
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-8"
spec:
  secretName: vault-tls
  issuerRef:
    name: private-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  privateKey:
    algorithm: RSA
    size: 2048
  subject:
    organizations:
      - system:nodes
  commonName: system:node:*.vault.svc.cluster.local
  isCA: false
  # TODO: Try restricting usages to digital signature, key encipherment, and
  # server auth
  usages:
  - digital signature
  - key encipherment
  - data encipherment
  - server auth
  - client auth
  dnsNames:
  - "*.vault-internal"
  - "*.vault-internal.vault.svc.cluster.local"
  - "*.vault"
  - "vault-internal.vault.svc.cluster.local"
  ipAddresses:
  - 127.0.0.1
  - 192.168.49.2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kes-policy
  namespace: vault
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-7"
data:
  kes-policy.hcl: |
    path "kv/data/minio-tenant/*" {
      capabilities = [ "create", "read" ]
    }
    path "kv/metadata/minio-tenant/*" {
      capabilities = [ "list", "delete" ]
    }
