apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: data-storage-service-db
  namespace: argocd
spec:
  source:
    helm: 
      valuesObject: 
        ingressHostName: dss-db.validation
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: metadata-service
  namespace: argocd
spec:
  source:
    helm: 
      valuesObject: 
        ingressHostName: metadata.validation
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: data-storage-service
  namespace: argocd
spec:
  source:
    helm: 
      valuesObject: 
        ingressHostName: data-storage.validation
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kg-exporter
  namespace: argocd
spec:
  source:
    helm: 
      valuesObject: 
        ingressHostName: kg-exporter.validation
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trade-off-service
  namespace: argocd
spec:
  source:
    helm: 
      valuesObject: 
        ingressHostName: tradeoff.validation
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prediction-service
  namespace: argocd
spec:
  source:
    helm: 
      valuesObject: 
        ingressHostName: prediction.validation
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  source:
    helm: 
      valuesObject: 
        cluster:
          name: nats-validation
