apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/apps/kernel
patches: 
  - path: patch-optional.yaml
  - path: patch-idrac-exporter.yaml
  - patch: |-
      - op: replace
        path: /spec/sources/0/helm/valuesObject/ingress/api/host
        value: glaciation-tenant.validation
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: minio-tenant
      namespace: argocd
  - patch: |-
      - op: replace
        path: /spec/sources/0/helm/valuesObject/ingress/console/host
        value: glaciation-tenant-console.validation
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: minio-tenant
      namespace: argocd
  - patch: |-
      - op: replace
        path: /spec/sources/0/helm/valuesObject/ingress/hosts/0/host
        value: gpm.validation
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: gatekeeper-policy-manager
      namespace: argocd
  - patch: |-
      - op: replace
        path: /spec/sources/0/helm/valuesObject/ingress/hosts/0/host
        value: vault.validation
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: vault
      namespace: argocd
  
