apiVersion: v1
kind: Namespace
metadata:
  name: spark-app
  labels:
    create-ca-bundle: "true"
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-8"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: spark-operator
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://kubeflow.github.io/spark-operator/
    chart: spark-operator
    targetRevision: 1.2.14
    helm:
      valuesObject:
        sparkJobNamespaces:
        - spark-app
        webhook:
          enable: true
  syncPolicy:
    automated:
     prune: true
     selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
