apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: validation-deployment
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/glaciation-heu/gitops-deployments
    path: bundle/validation
    targetRevision: deploy
    directory:
      recurse: true
  destination:
    namespace: argo-cd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: 
     prune: true 
     selfHeal: true 
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
