apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metadata-service
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dkg-engine
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://glaciation-heu.github.io/glaciation-metadata-service/helm-charts/
    chart: metadata-service
    targetRevision: 1.*.*
    helm:
      valuesObject:
        ingressHostName: metadata.integration
  syncPolicy:
    automated:
     prune: true
     selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
