apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats-operator
  namespace: argocd
  annotations:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dkg-engine
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://nats-io.github.io/k8s/helm/charts
    chart: nats-operator
    targetRevision: 0.8.3
    helm:
      valuesObject:
        cluster:
          ## Create a NATS Cluster when installing the operator
          create: false
  syncPolicy:
    automated:
     prune: true
     selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
