apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats-jetstream
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dkg-engine
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://nats-io.github.io/k8s/helm/charts
    chart: nats
    targetRevision: 1.2.6
    helm:
      valuesObject:
        config:
          serverNamePrefix: integration
        
          cluster:
            enabled: true
            replicas: 3

          jetstream:
            enabled: true

            fileStore:
              enabled: true
              dir: /data

              ############################################################
              # stateful set -> volume claim templates -> jetstream pvc
              ############################################################
              pvc:
                enabled: true
                size: 2Gi
                storageClassName: longhorn
                # accessModes:
                #   - ReadWriteOnce
                # defaults to "{{ include "nats.fullname" $ }}-js"
                # name:

              # defaults to the PVC size
              # maxSize:

            memoryStore:
              enabled: false
              # ensure that container has a sufficient memory limit greater than maxSize
              maxSize: 1Gi

            # merge:
            #   server_tags: az:integration

          mqtt:
            enabled: true

          websocket:
            enabled: true
            port: 8080
            noTLS: true

            sameOrigin: false
            allowedOrigins: []
            ingress:
              className: nginx
              path: /
              pathType: Prefix
              hosts:            
                - nats-websocket.integration

            # This will optionally specify what host:port for websocket
            # connections to be advertised in the cluster.
            # advertise: "host:port"

            # Set the handshake timeout for websocket connections
            # handshakeTimeout: 5s

  ignoreDifferences:
  - group: apps
    kind: StatefulSet
    jqPathExpressions:
      - '.spec.volumeClaimTemplates[]?'
  syncPolicy:
    automated:
     prune: true
     selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
