apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dkg-engine
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://nats-io.github.io/k8s/helm/charts
    chart: nats-operator
    targetRevision: 0.8.3
    helm:
      valuesObject:
        cluster:
          ## Create a NATS Cluster when installing the operator
          create: true

          name: nats-integration

          ## Choose namespace for cluster deployment if clusterScoped is set to true
          namespace: "dkg-engine"

          ## Nats version
          ## Image tags are listed here: https://hub.docker.com/_/nats?tab=tags
          version: 1.4.1

          ## Cluster Size
          size: 3

          ## Optional custom annotations to add to Pods in the cluster
          annotations: {}

          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi

          ## Client Authentication
          ## ref: https://github.com/nats-io/gnatsd#authentication
          ## note: token not supported only user/password will work with this chart version
          ##
          auth:
            enabled: true

            # NOTE: Only supported in Kubernetes v1.12+ clusters having the "TokenRequest" API enabled.
            enableServiceAccounts: false

            ## This is where you enter a username/password for 1 user
            username: "nats-user"
            password: "nuts-and-bolts"

            ## This is a where you can specify 2 or more users
            users: []
            # - username: "another-user-1"
            #   password: "another-password-1"
            # - username: "another-user-2"
            #   password: "another-password-2"
            #   permissions:
            #     publish: ["hello.*"]
            #     subscribe: ["hello.world"]

            defaultPermissions: {}
            # publish: ["SANDBOX.*"]
            # subscribe: ["PUBLIC.>"]

          tls:
            enabled: false
            # serverSecret:
            # routesSecret:

          ## Configuration Reload
          ## NOTE: Only supported in Kubernetes v1.12+.
          configReload:
            enabled: false
            registry: "docker.io"
            repository: "connecteverything/nats-server-config-reloader"
            tag: "0.2.2-v1alpha2"
            pullPolicy: "IfNotPresent"
            resources: {}
            # limits:
            #   cpu: 50m
            #   memory: 32Mi
            # requests:
            #   cpu: 10m
            #   memory: 32Mi

          ## Prometheus Metrics Exporter
          ##
          metrics:
            enabled: false
            registry: "docker.io"
            repository: "synadia/prometheus-nats-exporter"
            tag: "0.6.2"
            pullPolicy: "IfNotPresent"

            # Prometheus Operator ServiceMonitor config
            ##
            servicemonitor:
              enabled: false
              prometheusInstance: default
  syncPolicy:
    automated:
     prune: true
     selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
