apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: idmg-decision-engine
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    helm:
      valuesObject:
        ingress:
          hosts:
            databaseController: database-controller.validation
            dataGenerator: data-generator.validation
            plugin: plugin.validation
            model: model.validation