apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: idmg-decision-engine
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://idmg-pub.gitlab.io/helm-charts/
    chart: cf
    targetRevision: 0.*.*
  destination:
    namespace: idmg
    server: https://kubernetes.default.svc
  helm:
    valuesObject:
      ingress:
        hosts:
          databaseController: database-controller.integration
          dataGenerator: data-generator.integration
          plugin: plugin.integration
          model: model.integration
  syncPolicy:
    automated:
     prune: true
     selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
