apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: idmg-decision-engine
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://idmg-pub.gitlab.io/helm-charts/
    chart: cf
    targetRevision: 0.*.*
    helm:
      valuesObject:
        ingress:
          hosts:
            dataGenerator: data-generator.integration
            databaseController: database-controller.integration
            model: model.integration
            # external: external.integration
            prescoreplugin: prescoreplugin.integration
            scoreplugin: scoreplugin.integration
            cacheservice: cacheservice.integration
  destination:
    namespace: idmg
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
     prune: true
     selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true