apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: data-storage-service-db
  namespace: argocd
spec:
  source:
    helm: 
      valuesObject: 
        ingressHostName: dss-db.integration
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: metadata-service
  namespace: argocd
spec:
  source:
    helm: 
      valuesObject: 
        ingressHostName: metadata.integration
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: data-storage-service
  namespace: argocd
spec:
  source:
    helm: 
      valuesObject: 
        ingressHostName: data-storage.integration
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kg-exporter
  namespace: argocd
spec:
  source:
    helm: 
      valuesObject: 
        ingressHostName: kg-exporter.integration
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trade-off-service
  namespace: argocd
spec:
  source:
    helm: 
      valuesObject: 
        ingressHostName: tradeoff.integration              
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prediction-service
  namespace: argocd
spec:
  source:
    helm: 
      valuesObject: 
        ingressHostName: prediction.integration
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forecast-service
  namespace: argocd
spec:
  source:
    helm:
      valuesObject:
        ingressHostName: forecast.integration
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: replica-service
  namespace: argocd
spec:
  source:
    helm: 
      valuesObject:
        secretKey: "3366656464356265336466306662343365373332386165303834336338636231"
