apiVersion: batch/v1
kind: Job
metadata:
  name: anomaly-detection-job
spec:
  template:
    spec:
      containers:
      - name: anomaly-detection
        image: ghcr.io/glaciation-heu/dell-uc/workload-anomaly-detection:latest  # Use the locally built image
        imagePullPolicy: IfNotPresent  # Prevent Kubernetes from pulling the image from a remote registry
        command: ["python", "/app/workload_anomaly_detection.py"]
        args: ["--url", "http://metadata.uc2/api/v0/graph"]  # Pass URL as argument
      restartPolicy: Never
            nodeSelector:
        kubernetes.io/hostname: glaciation-worker01

