apiVersion: batch/v1
kind: Job
metadata:
  name: human-object-interaction-job
  namespace: uc2
spec:
  template:
    spec:
      containers:
      - name: human-object-interaction
        image:  ghcr.io/glaciation-heu/dell-uc/workload_human_object_interaction:latest  # Use the local Docker registry
        imagePullPolicy: IfNotPresent
        command: ["python", "/app/workload_object_distribution.py"]
        args: ["--url", "http://metadata.uc2/api/v0/graph"]  # Pass URL as argument
      restartPolicy: Never
      nodeSelector:
        kubernetes.io/hostname: glaciation-worker01

