apiVersion: batch/v1
kind: Job
metadata:
  name: human-object-interaction-job
spec:
  template:
    spec:
      containers:
      - name: human-object-interaction
        image:  ghcr.io/glaciation-heu/dell-uc/workload_human_object_interaction:latest  # Use the local Docker registry
        imagePullPolicy: IfNotPresent
      restartPolicy: Never
      nodeSelector:
        kubernetes.io/hostname: glaciation-worker01

