apiVersion: batch/v1
kind: Job
metadata:
  name: object-distribution-job
  namespace: uc2
spec:
  template:
    spec:
      containers:
      - name: object-distribution
        image:  ghcr.io/glaciation-heu/dell-uc/workload_object_distribution:latest # Use the local Docker registry
        imagePullPolicy:  Always        
        resources:
          requests:
            memory: "2Gi"
            cpu: "2"
            ephemeral-storage: "1Gi"
            nvidia.com/gpu: "0"
          limits:
            memory: "4Gi"
            cpu: "3"
            ephemeral-storage: "2Gi"
            nvidia.com/gpu: "0"                                                                                                               
        command: ["python", "/app/workload_object_distribution.py"] 
        args: ["--url", "http://metadata-service.dkg-engine.svc.cluster.local/api/v0/graph"] 
      restartPolicy: Never
      nodeSelector:
        kubernetes.io/hostname: glaciation-worker01

