apiVersion: batch/v1
kind: Job
metadata:
  name: operational-efficiency-job
spec:
  template:
    spec:
      containers:
      - name: operational-efficiency
        image: ghcr.io/glaciation-heu/dell-uc/workload_operational_efficiency:latest # Use the local Docker registry
        imagePullPolicy: IfNotPresent
        command: ["python", "workload_operational_efficiency.py"]
        args: ["--url", http://metadata.uc2/api/v0/graph]  # Pass URL as argument
      restartPolicy: Never
      nodeSelector:
        kubernetes.io/hostname: glaciation-worker01

