apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
  namespace: uc2
spec:
  template:
    metadata:
      annotations:
        glaciation-project.eu/start-time: "2025-07-01T10:30:07Z"
        glaciation-project.eu/worker-node-id: "https://kubernetes.local/#glaciation-worker03"

        glaciation-project.eu/memory-unit: "glc:Bytes"
        glaciation-project.eu/memory-used: "469487042.52"
        glaciation-project.eu/memory-allocated: "12884901888"
        glaciation-project.eu/memory-demanded: "6442450944"

        glaciation-project.eu/cpu-unit: "glc:Core"
        glaciation-project.eu/cpu-used: "0.002"
        glaciation-project.eu/cpu-allocated: "2"
        glaciation-project.eu/cpu-demanded: "1"

        glaciation-project.eu/storage-unit: "glc:Bytes"
        glaciation-project.eu/storage-used: "102400"
        glaciation-project.eu/storage-allocated: "104857600"
        glaciation-project.eu/storage-demanded: "20971520"

        glaciation-project.eu/network-unit: "glc:Bytes"
        glaciation-project.eu/network-used: "0.349"
        glaciation-project.eu/network-allocated: "1"
        glaciation-project.eu/network-demanded: "0.1"

        glaciation-project.eu/energy-unit: "glc:Milliwatt"
        glaciation-project.eu/energy-used: "0.025"
        glaciation-project.eu/energy-allocated: "0.5"
        glaciation-project.eu/energy-demanded: "0.01"

        glaciation-project.eu/workload-id: "workload-test-job"
    spec:
      containers:
      - name: test-container  
        image: ghcr.io/glaciation-heu/dell-uc/workload_test:latest
        imagePullPolicy: IfNotPresent
        command: ["python", "/app/workload.py"]  # Moved inside the container definition
        args: ["--url", http://metadata.validation/api/v0/graph]
      restartPolicy: Never
      nodeSelector:
        kubernetes.io/hostname: glaciation-worker01

