apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - local-path-storage.yaml
  - nginx-ingress.yaml
  - jena-fuseki.yaml
  - jena-fuseki-exporter.yaml
  - longhorn.yaml
  - jenkins.yaml
