apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-device-plugin
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: default
  sources:
    - chart: nvidia-device-plugin
      repoURL: https://nvidia.github.io/k8s-device-plugin/stable
      targetRevision: 0.*.*
      helm:
        valuesObject:
          gfd:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: nvidia-device-plugin
  syncPolicy:
    automated: 
     prune: true 
     selfHeal: true 
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
