apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/apps/base
patches:
  - path: patch-waves.yaml
  - patch: |-
      - op: replace
        path: /spec/source/helm/valuesObject/ingressHostName
        value: jena-fuseki.uc2
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: jena-fuseki
      namespace: argocd
  - patch: |-
      - op: replace
        path: /spec/source/helm/valuesObject/controller/config/entries
        value: "10.14.2.5"
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: nginx
      namespace: argocd