apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/apps/base
patches:
  - path: patch-waves.yaml
  - path: patch-optional.yaml
  - patch: |-
      - op: replace
        path: /spec/source/helm/valuesObject/ingressHostName
        value: jena-fuseki.validation
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: jena-fuseki
      namespace: argocd
