apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: nginx
  namespace: argocd
spec:
  source:
    helm:
      valuesObject:      
        controller:
          config:
            entries:
              external-status-address: "10.14.2.5"