apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true  
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://glaciation-heu.github.io/monitoring-stack/helm-charts/
    chart: monitoring-stack
    targetRevision: 1.0.*
    helm:
      valuesObject:
        prometheus:
          server:
            ingress: 
              enabled: true
              ingressClassName: nginx
              hosts:
                - prometheus.integration

        telegraf:
          resources:
            requests:
              memory: 1Gi
              cpu: 1
            limits:
              memory: 1Gi
              cpu: 1

          config:
            agent:
              metric_batch_size: 50000
              metric_buffer_limit: 500000
              interval: "5s"
              flush_interval: "5s"
              debug: true
            outputs:      
              - influxdb_v2:
                  urls:
                    - "http://monitoring-stack-influxdb2"
                  token: encrypted
                  organization: "influxdata"
                  bucket: "prometheus"            
                  timeout: "30s"
                  metric_batch_size: 50000
                  metric_buffer_limit: 500000

        influxdb:
          enabled: true
        
        kubernetes-event-exporter:
          config:
            receivers:
            - name: "dump"
              stdout:
                deDot: true
            - name: "loki"
              loki:
                streamLabels:
                  stream: kube-events
                url: http://monitoring-stack-loki:3100/loki/api/v1/push

        grafana:
          adminPassword: donkeyhot
          ingress:
            enabled: true
            ingressClassName: nginx
            path: /
            pathType: Prefix
            hosts:
              - grafana.integration
          grafana.ini:
            auth.anonymous:
              enabled: true
            auth:
              signout_redirect_url: /
            users:
              viewers_can_edit: true

        kepler:
          enabled: true

  syncPolicy:
    automated:
     prune: true
     selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
