apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://kedacore.github.io/charts'
    targetRevision: 2.14.0
    helm:
      values: |        
        resources:
          operator:
            limits:
              cpu: 1
              memory: 1000Mi
              nvidia.com/gpu: 0
              ephemeral-storage: 5Mi
            requests:
              cpu: 100m
              memory: 100Mi
              nvidia.com/gpu: 0
              ephemeral-storage: 1Mi
          metricServer:
            limits:
              cpu: 1
              memory: 1000Mi
              nvidia.com/gpu: 0
              ephemeral-storage: 5Mi
            requests:
              cpu: 100m
              memory: 100Mi
              nvidia.com/gpu: 0
              ephemeral-storage: 1Mi
          webhooks:
            limits:
              cpu: 1
              memory: 1000Mi
              nvidia.com/gpu: 0
              ephemeral-storage: 5Mi
            requests:
              cpu: 100m
              memory: 100Mi
              nvidia.com/gpu: 0
              ephemeral-storage: 1Mi
    chart: keda
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: keda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
