apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: idmg-decision-engine
  namespace: argocd
spec:
  helm:
    valuesObject:
      ingress:
        hosts:
          databaseController: database-controller.uc2
          dataGenerator: data-generator.uc2
          plugin: plugin.uc2
          model: model.uc2