apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"opentraj"},"name":"opentraj-workload","namespace":"dell-uc2"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"opentraj"}},"template":{"metadata":{"labels":{"app":"opentraj"}},"spec":{"containers":[{"command":["python","Dell-UC2_OpenTraj_workload.py"],"image":"pournima2024/opentraj-workload:latest","imagePullPolicy":"Always","name":"opentraj-container","resources":{"limits":{"cpu":"2","memory":"8Gi"},"requests":{"cpu":"1","memory":"4Gi"}},"volumeMounts":[{"mountPath":"/app/OpenTraj/datasets","name":"opentraj-datasets"}]}],"volumes":[{"hostPath":{"path":"/mnt/data/DELL-UC/OpenTraj/datasets","type":"Directory"},"name":"opentraj-datasets"}]}}}}
  creationTimestamp: "2025-01-10T01:29:41Z"
  generation: 1
  labels:
    app: opentraj
  name: opentraj-workload
  namespace: dell-uc2
  resourceVersion: "21489637"
  uid: 14c34488-30f7-42af-b317-69226ae2dc92
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: opentraj
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: opentraj
    spec:
      containers:
      - command:
        - python
        - Dell-UC2_OpenTraj_workload.py
        image: pournima2024/opentraj-workload:latest
        imagePullPolicy: Always
        name: opentraj-container
        resources:
          limits:
            cpu: "2"
            memory: 8Gi
          requests:
            cpu: "1"
            memory: 4Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/OpenTraj/datasets
          name: opentraj-datasets
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /mnt/data/DELL-UC/OpenTraj/datasets
          type: Directory
        name: opentraj-datasets
status:
  conditions:
  - lastTransitionTime: "2025-01-10T01:29:41Z"
    lastUpdateTime: "2025-01-10T01:29:43Z"
    message: ReplicaSet "opentraj-workload-65bd659578" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-01-17T01:11:32Z"
    lastUpdateTime: "2025-01-17T01:11:32Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 1
  replicas: 2
  unavailableReplicas: 2
  updatedReplicas: 2
