apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
spec:
  source:
    helm:
      valuesObject:
        prometheus:
          server:
            resources:
              limits:
                cpu: 1
                memory: 4Gi
              requests:
                cpu: 1
                memory: 4Gi
            global:
              external_labels:
                cluster: integration
            alertmanager:
              ingress:
                enabled: true
                className: nginx
                hosts:
                  - alertmanager.integration
