apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: monitoring-stack
  namespace: argocd
spec:
  source:
    helm:
      valuesObject:
        prometheus:
          server:
            resources:
              limits:
                cpu: 4
                memory: 8Gi
              requests:
                cpu: 1
                memory: 4Gi
