apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/apps/kernel
patches: 
  - patch: |-
      - op: replace
        path: /spec/sources/0/helm/valuesObject/ingress/api/host
        value: glaciation-tenant.uc2
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: minio-tenant
      namespace: argocd
  - patch: |-
      - op: replace
        path: /spec/sources/0/helm/valuesObject/ingress/console/host
        value: glaciation-tenant-console.uc2
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: minio-tenant
      namespace: argocd
  - patch: |-
      - op: replace
        path: /spec/sources/0/helm/valuesObject/ingress/hosts/0/host
        value: gpm.uc2
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: gatekeeper-policy-manager
      namespace: argocd
  - patch: |-
      - op: replace
        path: /spec/sources/0/helm/valuesObject/ingress/hosts/0/host
        value: vault.uc2
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: vault
      namespace: argocd
  - patch: |-
      - op: replace
        path: /spec/sources/0/helm/valuesObject/ingress/hosts/0/host
        value: prometheus.uc2
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: vault
      namespace: monitoring
  - patch: |-
      - op: replace
        path: /spec/sources/0/helm/valuesObject/ingress/hosts/3/host
        value: grafana.uc2
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: vault
      namespace: monitoring
