apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: monitoring-stack
  namespace: argocd
spec:
  source:
    helm:
      valuesObject:
        prometheus:
          server:
            ingress: 
              hosts:
                - prometheus.uc2
    
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: monitoring-stack
  namespace: argocd
spec:
  source:
    helm:
      valuesObject:
        grafana:
          ingress: 
            hosts:
              - grafana.uc2

