apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/apps/data-sanitization
patches: 
  - patch: |-
      - op: replace
        path: /spec/sources/0/helm/valuesObject/ingress/hosts/0/host
        value: data-sanitization.validation
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: data-sanitization
      namespace: argocd
  - patch: |-
      - op: replace
        path: /spec/sources/0/helm/valuesObject/ingress/hosts/0/host
        value: spark-history-server.validation
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: spark-history-server
      namespace: argocd
