apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uc3-workload-service
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: uc3
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://glaciation-heu.github.io/sap-uc3
    chart: secure-collab-comp
    targetRevision: 0.*.*
    helm:
      valuesObject:
        ingressHostName: uc3-workload.integration
  syncPolicy:
    automated:
     prune: true
     selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
