apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./manual/vault-extras.yaml
  - ./manual/setup-ca-and-bundle.yaml
  - ./manual/minio-sse-smoke-tests.yaml
  - ./manual/vault-init.yaml
  - ./manual/gatekeeper-smoke-tests.yaml
  # - ./manual/set-default-resource-requests-and-limits.yaml
  # - ./manual/gatekeeper-resource-constraint-templates.yaml
  # - ./manual/gatekeeper-resource-constraints.yaml
  - cert-manager.yaml
  - gatekeeper.yaml
  - trust-manager.yaml
  - vault.yaml
  - gatekeeper-policy-manager.yaml
  - replicator.yaml
  - minio-tenant.yaml
