apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - gatekeeper.yaml
  - set-multi-tenant-node-filtering.yaml
  - validate-multi-tenant-node-filtering.yaml
  - setup-ca-and-bundle.yaml
  - trust-manager.yaml
  - vault.yaml
  - gatekeeper-policy-manager.yaml
  - replicator.yaml
  - ./manual/vault-init.yaml
  - ./manual/gatekeeper-smoke-tests.yaml