apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./manual/gatekeeper-smoke-tests.yaml
  - ./manual/minio-sse-smoke-tests.yaml
  - ./manual/set-default-resource-requests-and-limits.yaml
  - ./manual/setup-ca-and-bundle.yaml
  - ./manual/validate-resource-requests-and-limits.yaml
  - ./manual/vault-certificate.yaml
  - ./manual/vault-init.yaml
  - cert-manager.yaml
  - gatekeeper.yaml
  - gatekeeper-policy-manager.yaml
  - minio-tenant.yaml
  - replicator.yaml
  - trust-manager.yaml
  - vault.yaml
