apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - admission-control.yaml
  - certificate-management.yaml
  - data-wrapping.yaml
  - data-sanitization.yaml
  - gatekeeper-policy-manager.yaml
