apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uc4-workload
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: uc4-workload
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://glaciationIPTO.github.io/server_procs/helm-charts/
    chart: uc4-workload
    targetRevision: 1.*.*
  syncPolicy:
    automated:
     prune: true
     selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true