apiVersion: v1
kind: Namespace
metadata:
  name: vault
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
  labels:
    create-ca-bundle: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-kes-secret
  namespace: vault
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
    replicator.v1.mittwald.de/replicate-from: minio-tenant/minio-kes-secret
data: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kes-policy
  namespace: vault
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
data:
  kes-policy.hcl: |
    path "kv/data/minio-tenant/*" {
      capabilities = [ "create", "read" ]
    }
    path "kv/metadata/minio-tenant/*" {
      capabilities = [ "list", "delete" ]
    }
